"""04_created_citation_and_callback_table.py

Revision ID: 1bd3801f7a39
Revises: 1b0437e42c5d
Create Date: 2024-04-02 17:49:22.033923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bd3801f7a39'
down_revision: Union[str, None] = '1b0437e42c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('park_pliant_callback',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('citation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('lot_code', sa.String(), nullable=False),
    sa.Column('issued', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('amount_due', sa.Float(), nullable=False),
    sa.Column('fk_violation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_violation_id'], ['violation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citation')
    op.drop_table('park_pliant_callback')
    # ### end Alembic commands ###
