"""06_record_id_and_lot_id_added

Revision ID: c74e0dcc8092
Revises: 5d573bfe9dae
Create Date: 2024-04-18 11:53:32.308098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74e0dcc8092'
down_revision: Union[str, None] = '5d573bfe9dae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation', sa.Column('parking_lot_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violation', 'parking_lot_id')
    # ### end Alembic commands ###
