"""07_location_id_in_push_payment

Revision ID: 2800adc54d13
Revises: fdbc006b21df
Create Date: 2024-04-17 00:48:42.991336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2800adc54d13'
down_revision: Union[str, None] = 'c74e0dcc8092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('push_payment', sa.Column('location_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('push_payment', 'location_id')
    # ### end Alembic commands ###
