"""08_inout_policy

Revision ID: ae337e0a42ae
Revises: 2800adc54d13
Create Date: 2024-04-19 14:26:40.115132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae337e0a42ae'
down_revision: Union[str, None] = '2800adc54d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_parkinglot', sa.Column('is_in_out_policy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connect_parkinglot', 'is_in_out_policy')
    # ### end Alembic commands ###
