"""11_total_amount_in_sessions

Revision ID: 907a5ed37d44
Revises: 7324be18baa9
Create Date: 2024-05-27 18:16:35.133117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907a5ed37d44'
down_revision: Union[str, None] = 'ea71eb81702d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('total_paid_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'total_paid_amount')
    # ### end Alembic commands ###
