"""11_provider_cred_added

Revision ID: c917159a02e4
Revises: 907a5ed37d44
Create Date: 2024-06-04 16:56:33.841514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c917159a02e4'
down_revision: Union[str, None] = '907a5ed37d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_creds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text_key', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expire_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('logo', sa.String(), nullable=True),
    sa.Column('fk_provider_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_creds')
    # ### end Alembic commands ###
