"""12_provider_feature_to_feature_change

Revision ID: 2c6c7d69457f
Revises: c917159a02e4
Create Date: 2024-06-04 18:47:53.019293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c6c7d69457f'
down_revision: Union[str, None] = 'c917159a02e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('provider_feature', 'feature')
    op.drop_constraint('feature_event_type_fk_provider_feature_fkey', 'feature_event_type', type_='foreignkey')
    op.drop_constraint('feature_url_path_fk_provider_feature_fkey', 'feature_url_path', type_='foreignkey')
    op.alter_column('feature_event_type', 'fk_provider_feature', new_column_name='fk_feature')
    op.alter_column('feature_url_path', 'fk_provider_feature', new_column_name='fk_feature')
    op.create_foreign_key('feature_event_type_fk_feature_fkey', 'feature_event_type', 'feature', ['fk_feature'], ['id'])
    op.create_foreign_key('feature_url_path_fk_feature_fkey', 'feature_url_path', 'feature', ['fk_feature'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('feature', 'provider_feature')
    op.drop_constraint('feature_event_type_fk_feature_fkey', 'feature_event_type', type_='foreignkey')
    op.drop_constraint('feature_url_path_fk_feature_fkey', 'feature_url_path', type_='foreignkey')
    op.alter_column('feature_event_type', 'fk_feature', new_column_name='fk_provider_feature')
    op.alter_column('feature_url_path', 'fk_feature', new_column_name='fk_provider_feature')
    op.create_foreign_key('feature_event_type_fk_provider_feature_fkey', 'feature_event_type', 'provider_feature', ['fk_provider_feature'], ['id'])
    op.create_foreign_key('feature_url_path_fk_provider_feature_fkey', 'feature_url_path', 'provider_feature', ['fk_provider_feature'], ['id'])
    # ### end Alembic commands ###
