"""13_provider_feature_added

Revision ID: f6d94b1578ed
Revises: 2c6c7d69457f
Create Date: 2024-06-05 12:15:20.563184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d94b1578ed'
down_revision: Union[str, None] = '2c6c7d69457f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_provider_id', sa.Integer(), nullable=False),
    sa.Column('fk_feature', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_feature'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['fk_provider_id'], ['provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provider_feature')
    # ### end Alembic commands ###
