"""15_parkinglot_provider_feature_added

Revision ID: 72d68ff7aeb0
Revises: 234c935d91c6
Create Date: 2024-06-05 14:46:50.316414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d68ff7aeb0'
down_revision: Union[str, None] = '234c935d91c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parkinglot_provider_feature',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_provider_connect', sa.Integer(), nullable=False),
    sa.Column('fk_feature', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_feature'], ['feature.id'], ),
    sa.ForeignKeyConstraint(['fk_provider_connect'], ['provider_connect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parkinglot_provider_feature')
    # ### end Alembic commands ###
