"""18_provider_creds_on_sub_task

Revision ID: f3014576140c
Revises: 72d68ff7aeb0
Create Date: 2024-06-06 17:12:13.353902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3014576140c'
down_revision: Union[str, None] = '72d68ff7aeb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint('sub_task_fk_provider_fkey', 'sub_task', type_='foreignkey')
    op.alter_column('sub_task', 'fk_provider', new_column_name='fk_provider_creds_id')
    op.create_foreign_key('sub_task_fk_provider_creds_fkey', 'sub_task', 'provider_creds', ['fk_provider_creds_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sub_task_fk_provider_creds_fkey', 'sub_task', type_='foreignkey')
    op.alter_column('sub_task', 'fk_provider_creds_id', new_column_name='fk_provider')
    op.create_foreign_key('sub_task_fk_provider_fkey', 'sub_task', 'provider', ['fk_provider_id'], ['id'])
    # ### end Alembic commands ###
