"""19_provider_creds_on_sub_task

Revision ID: ea05b3632f7b
Revises: f3014576140c
Create Date: 2024-06-06 17:36:21.363562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea05b3632f7b'
down_revision: Union[str, None] = 'f3014576140c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('provider_connect_fk_provider_id_fkey', 'provider_connect', type_='foreignkey')
    op.alter_column('provider_connect', 'fk_provider_id', new_column_name='fk_provider_creds_id')
    op.create_foreign_key('provider_connect_fk_provider_creds_id_fkey', 'provider_connect', 'provider_creds', ['fk_provider_creds_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('provider_connect_fk_provider_creds_id_fkey', 'provider_connect', type_='foreignkey')
    op.alter_column('provider_connect', 'fk_provider_creds_id', new_column_name='fk_provider_id')
    op.create_foreign_key('provider_connect_fk_provider_id_fkey', 'provider_connect', 'provider', ['fk_provider_id'], ['id'])
    # ### end Alembic commands ###
