"""20_feature_event_type_modified

Revision ID: e508029ff1a2
Revises: ea05b3632f7b
Create Date: 2024-06-07 11:40:24.168739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e508029ff1a2'
down_revision: Union[str, None] = 'ea05b3632f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_event_type', sa.Column('fk_parkinglot_provider_feature', sa.Integer(), nullable=True))
    op.drop_constraint('feature_event_type_fk_provider_connect_fkey', 'feature_event_type', type_='foreignkey')
    op.drop_constraint('feature_event_type_fk_feature_fkey', 'feature_event_type', type_='foreignkey')
    op.create_foreign_key(None, 'feature_event_type', 'parkinglot_provider_feature', ['fk_parkinglot_provider_feature'], ['id'])
    op.drop_column('feature_event_type', 'fk_feature')
    op.drop_column('feature_event_type', 'fk_provider_connect')
    op.alter_column('provider_connect', 'fk_provider_creds_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sub_task', type_='foreignkey')
    op.alter_column('sub_task', 'fk_provider_creds_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('provider_connect_fk_provider_id_fkey', 'provider_connect', 'provider', ['fk_provider_creds_id'], ['id'])
    op.alter_column('provider_connect', 'fk_provider_creds_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('feature_event_type', sa.Column('fk_provider_connect', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feature_event_type', sa.Column('fk_feature', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'feature_event_type', type_='foreignkey')
    op.create_foreign_key('feature_event_type_fk_feature_fkey', 'feature_event_type', 'feature', ['fk_feature'], ['id'])
    op.create_foreign_key('feature_event_type_fk_provider_connect_fkey', 'feature_event_type', 'provider_connect', ['fk_provider_connect'], ['id'])
    op.drop_column('feature_event_type', 'fk_parkinglot_provider_feature')
    # ### end Alembic commands ###
