"""21_provider_modified

Revision ID: 03a8e7383225
Revises: e508029ff1a2
Create Date: 2024-06-07 11:44:20.311618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03a8e7383225'
down_revision: Union[str, None] = 'e508029ff1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('provider', 'logo')
    op.drop_column('provider', 'text_key')
    op.drop_column('provider', 'meta_data')
    op.drop_column('provider', 'access_token')
    op.drop_column('provider', 'client_id')
    op.drop_column('provider', 'expire_time')
    op.drop_column('provider', 'api_endpoint')
    op.drop_column('provider', 'client_secret')
    op.drop_column('provider', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider', sa.Column('api_endpoint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('expire_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('provider', sa.Column('text_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('provider', sa.Column('logo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('provider', 'description')
    # ### end Alembic commands ###
