"""23_provider_meta_data_added

Revision ID: 96fe2b5639be
Revises: 3ab1dd2a5789
Create Date: 2024-06-07 16:16:49.452906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96fe2b5639be'
down_revision: Union[str, None] = '3ab1dd2a5789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'meta_data')
    # ### end Alembic commands ###
