"""23_feature_to_provider_id_in_url_path

Revision ID: 7f2376415fbb
Revises: 16cd17eacf57
Create Date: 2024-06-11 18:56:28.030031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f2376415fbb'
down_revision: Union[str, None] = '16cd17eacf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_url_path', sa.Column('fk_provider_feature', sa.Integer(), nullable=True))
    op.drop_constraint('feature_url_path_fk_feature_fkey', 'feature_url_path', type_='foreignkey')
    op.create_foreign_key(None, 'feature_url_path', 'provider_feature', ['fk_provider_feature'], ['id'])
    op.drop_column('feature_url_path', 'fk_feature')
    op.alter_column('provider', 'auth_level',
               existing_type=postgresql.ENUM('GLOBAL', 'CUSTOMER', 'PARKING_LOT', name='authlevel'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider', 'auth_level',
               existing_type=postgresql.ENUM('GLOBAL', 'CUSTOMER', 'PARKING_LOT', name='authlevel'),
               nullable=True)
    op.add_column('feature_url_path', sa.Column('fk_feature', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feature_url_path', type_='foreignkey')
    op.create_foreign_key('feature_url_path_fk_feature_fkey', 'feature_url_path', 'feature', ['fk_feature'], ['id'])
    op.drop_column('feature_url_path', 'fk_provider_feature')
    # ### end Alembic commands ###
