"""24_add_organization

Revision ID: 3faf787a8246
Revises: 7f2376415fbb
Create Date: 2024-06-25 14:43:42.526594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3faf787a8246'
down_revision: Union[str, None] = '7f2376415fbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Insert a record with org_id 23
    op.execute(
        """
        INSERT INTO organization (org_id, contact_name, contact_email, created_at, updated_at)
        VALUES (23, 'Default Contact', 'contact@example.com', NOW(), NOW())
        """
    )

    # Add the new column with a default value
    op.add_column('connect_parkinglot', sa.Column('fk_organization_id', sa.Integer(), server_default='1'))
    # Update existing rows to have the default value (if necessary)
    op.execute('UPDATE connect_parkinglot SET fk_organization_id = 1 WHERE fk_organization_id IS NULL')
    # Alter the column to make it non-nullable
    op.alter_column('connect_parkinglot', 'fk_organization_id', existing_type=sa.Integer(), nullable=False,
                    server_default=None)
    # Create the foreign key constraint
    op.create_foreign_key(None, 'connect_parkinglot', 'organization', ['fk_organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'connect_parkinglot', type_='foreignkey')
    op.drop_column('connect_parkinglot', 'fk_organization_id')
    op.drop_table('organization')
    # ### end Alembic commands ###
