"""27_add_column_parking_spot_id_in_violation

Revision ID: 3b2abca24cc6
Revises: 7486d664aa2a
Create Date: 2024-07-13 13:41:51.333613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2abca24cc6'
down_revision: Union[str, None] = '7486d664aa2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation', sa.Column('parking_spot_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violation', 'parking_spot_id')
    # ### end Alembic commands ###
