"""28_added_lot_contact_name_parking_lot

Revision ID: 708cf35bf6b7
Revises: 3b2abca24cc6
Create Date: 2024-07-17 11:03:16.018665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '708cf35bf6b7'
down_revision: Union[str, None] = '3b2abca24cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_parkinglot', sa.Column('contact_name', sa.String(), nullable=True))
    op.add_column('connect_parkinglot', sa.Column('parking_lot_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'provider_connect', 'connect_parkinglot', ['fk_connect_parkinglot_id'], ['id'])
    op.create_foreign_key(None, 'provider_connect', 'provider_creds', ['fk_provider_creds_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'provider_connect', type_='foreignkey')
    op.drop_constraint(None, 'provider_connect', type_='foreignkey')
    op.drop_column('connect_parkinglot', 'parking_lot_name')
    op.drop_column('connect_parkinglot', 'contact_name')
    # ### end Alembic commands ###
