"""set_org_name

Revision ID: 5ae0c1c7ee27
Revises: 708cf35bf6b7
Create Date: 2024-07-24 13:31:42.367056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ae0c1c7ee27'
down_revision: Union[str, None] = '708cf35bf6b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('org_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'org_name')
    # ### end Alembic commands ###
