"""31_added_nph_in_connnect_parking_lot

Revision ID: 888182f00c3f
Revises: feb340f7daed
Create Date: 2024-09-12 13:18:41.749617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '888182f00c3f'
down_revision: Union[str, None] = 'feb340f7daed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_parkinglot', sa.Column('nph_start_at', sa.Time(), nullable=True))
    op.add_column('connect_parkinglot', sa.Column('nph_end_at', sa.Time(), nullable=True))
    op.add_column('connect_parkinglot', sa.Column('nph_interval_in_days', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connect_parkinglot', 'nph_interval_in_days')
    op.drop_column('connect_parkinglot', 'nph_end_at')
    op.drop_column('connect_parkinglot', 'nph_start_at')
    # ### end Alembic commands ###
