"""33_added_nph_column_in_sessions

Revision ID: aacc26de6a1d
Revises: c68e1590c3bf
Create Date: 2024-09-16 22:56:01.312216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aacc26de6a1d'
down_revision: Union[str, None] = 'c68e1590c3bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('has_nph_task', sa.Boolean(), server_default=sa.false(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'has_nph_task')
    # ### end Alembic commands ###
