"""34_create_nph_configuration_table

Revision ID: c21c05d9e8b7
Revises: aacc26de6a1d
Create Date: 2024-09-17 15:26:41.394468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c21c05d9e8b7'
down_revision: Union[str, None] = 'aacc26de6a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nph_configuration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_connect_parkinglot_id', sa.Integer(), nullable=False),
    sa.Column('nph_start_at', sa.Time(), nullable=False),
    sa.Column('nph_end_at_interval_minutes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('nph_overstay_limit_in_minutes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_connect_parkinglot_id'], ['connect_parkinglot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nph_configuration')
    # ### end Alembic commands ###
