"""35_enforcement_table

Revision ID: d63112b5bf36
Revises: c21c05d9e8b7
Create Date: 2024-10-03 19:49:31.417878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd63112b5bf36'
down_revision: Union[str, None] = 'c21c05d9e8b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enforcement_response_store',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate_number', sa.String(), nullable=True),
    sa.Column('fk_provider_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.Column('fk_session', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_provider_id'], ['provider.id'], ),
    sa.ForeignKeyConstraint(['fk_session'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enforcement_response_store')
    # ### end Alembic commands ###
