"""36_removed_relation_and_some_field_from_enforcement

Revision ID: e98d5a449920
Revises: d63112b5bf36
Create Date: 2024-10-10 21:37:12.041229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e98d5a449920'
down_revision: Union[str, None] = 'd63112b5bf36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enforcement_response_store', 'fk_session')
    op.drop_column('enforcement_response_store', 'plate_number')
    op.drop_column('enforcement_response_store', 'fk_provider_id')
    op.drop_column('enforcement_response_store', 'ticket_number')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enforcement_response_store', sa.Column('ticket_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('enforcement_response_store', sa.Column('fk_provider_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('enforcement_response_store', sa.Column('plate_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('enforcement_response_store', sa.Column('fk_session', sa.INTEGER(), autoincrement=False, nullable=True))
