"""37_add_alert_status_in_task_table

Revision ID: 15f22f33de6c
Revises: e98d5a449920
Create Date: 2024-10-16 01:10:16.946544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15f22f33de6c'
down_revision: Union[str, None] = 'e98d5a449920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('alert_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'alert_status')
    # ### end Alembic commands ###
