"""43_parking_time

Revision ID: 5b1e57d3bb6a
Revises: 743705b2e360
Create Date: 2024-12-08 20:43:54.568914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b1e57d3bb6a'
down_revision: Union[str, None] = '743705b2e360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_time',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fk_connect_parkinglot_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fk_connect_parkinglot_id'], ['connect_parkinglot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # Define the enum type
    payment_window_operation_type_enum = sa.Enum(
        'always_free_parking', 'always_paid_parking', 'specified_paid_timing',
        name='paymentwindowoperationtype'
    )
    
    # Create the enum type in the database
    payment_window_operation_type_enum.create(op.get_bind())

    op.add_column('connect_parkinglot', sa.Column('payment_window_operation_type', sa.Enum('always_free_parking', 'always_paid_parking', 'specified_paid_timing', name='paymentwindowoperationtype'), nullable=False, server_default='always_paid_parking'))
    op.add_column('connect_parkinglot', sa.Column('maximum_park_time', sa.Integer(), nullable=True))
    op.drop_column('connect_parkinglot', 'enforced_parking_rule_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_parkinglot', sa.Column('enforced_parking_rule_type', postgresql.ENUM('paid_time', 'twenty_four_hour_free_window', 'do_nothing', name='enforcedparkingruletype'), server_default=sa.text("'do_nothing'::enforcedparkingruletype"), autoincrement=False, nullable=True))
    
    op.drop_column('connect_parkinglot', 'maximum_park_time')
    op.drop_column('connect_parkinglot', 'payment_window_operation_type')
    op.execute("DROP TYPE paymentwindowoperationtype;")
    op.drop_table('parking_time')
    # ### end Alembic commands ###
