"""44_add_column_maximum_park_time_units_in_connect_parkinglot_table

Revision ID: cfad0b68d060
Revises: 5b1e57d3bb6a
Create Date: 2024-12-09 16:25:44.121839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfad0b68d060'
down_revision: Union[str, None] = '5b1e57d3bb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Define the enum type
    maximum_park_time_unit = sa.Enum(
        'minutes', 'hours', 'seconds',
        name='timeunits'
    )
    
    # Create the enum type in the database
    maximum_park_time_unit.create(op.get_bind())

    op.add_column('connect_parkinglot', sa.Column('maximum_park_time_unit', sa.Enum('minutes', 'hours', 'seconds', name='timeunits'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connect_parkinglot', 'maximum_park_time_unit')
    # ### end Alembic commands ###
