"""45_removed_nph_table_and_column_from_connect_parking_lot

Revision ID: ec527598fd5d
Revises: cfad0b68d060
Create Date: 2024-12-13 19:04:38.206684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec527598fd5d'
down_revision: Union[str, None] = 'cfad0b68d060'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nph_configuration')
    op.drop_column('connect_parkinglot', 'nph_end_at')
    op.drop_column('connect_parkinglot', 'nph_overstay_limit_in_minutes')
    op.drop_column('connect_parkinglot', 'nph_start_at')
    op.drop_column('connect_parkinglot', 'nph_interval_in_days')


def downgrade() -> None:
    pass
