"""48_alter_maximum_park_time

Revision ID: 6a7b5ae043f8
Revises: e6522acd0f90
Create Date: 2025-01-06 18:09:05.262962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a7b5ae043f8'
down_revision: Union[str, None] = 'e6522acd0f90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_parkinglot', sa.Column('maximum_park_time_in_minutes', sa.Integer(), nullable=True))
    op.drop_column('connect_parkinglot', 'maximum_park_time')
    op.drop_column('connect_parkinglot', 'maximum_park_time_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_parkinglot', sa.Column('maximum_park_time_unit', postgresql.ENUM('minutes', 'hours', 'seconds', name='timeunits'), autoincrement=False, nullable=True))
    op.add_column('connect_parkinglot', sa.Column('maximum_park_time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('connect_parkinglot', 'maximum_park_time_in_minutes')
    # ### end Alembic commands ###
