"""49_alter_contact_email_to_nullable_in_connectParkingLot

Revision ID: b1011d9f4544
Revises: 6a7b5ae043f8
Create Date: 2025-01-19 18:12:09.928360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1011d9f4544'
down_revision: Union[str, None] = '6a7b5ae043f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connect_parkinglot', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connect_parkinglot', 'contact_email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
