"""50_add_spot_name_in_task

Revision ID: 50cb10f605e7
Revises: b1011d9f4544
Create Date: 2025-01-23 11:30:46.700058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50cb10f605e7'
down_revision: Union[str, None] = 'b1011d9f4544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('sessions', sa.Column('parking_spot_name', sa.String(), nullable=True))
    op.add_column('task', sa.Column('parking_spot_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'parking_spot_name')
    op.drop_column('sessions', 'parking_spot_name')
