"""52_add_soft_delete

Revision ID: 6ae8bf6b5e8b
Revises: 4ee636f7ba9d
Create Date: 2025-03-04 10:38:15.311588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae8bf6b5e8b'
down_revision: Union[str, None] = '4ee636f7ba9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_task', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('provider_creds', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_task', 'deleted_at')
    op.drop_column('provider_creds', 'deleted_at')
    # ### end Alembic commands ###
