"""53_added_event_at_in_session_log

Revision ID: 1dac09aba159
Revises: 6ae8bf6b5e8b
Create Date: 2025-03-11 11:46:45.867980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1dac09aba159'
down_revision: Union[str, None] = '6ae8bf6b5e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_log', sa.Column('event_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_log', 'event_at')
    # ### end Alembic commands ###
