"""54_add_inactivation_id_in_violation

Revision ID: 58e7e131ddb5
Revises: 1dac09aba159
Create Date: 2025-03-16 22:59:52.279198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58e7e131ddb5'
down_revision: Union[str, None] = '1dac09aba159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('violation', sa.Column('citation_inactivation_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('violation', 'citation_inactivation_id')
    # ### end Alembic commands ###
