"""55_add_deleted_at_in_sessions_table

Revision ID: 96e7927862ff
Revises: 58e7e131ddb5
Create Date: 2025-03-17 16:59:20.677610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e7927862ff'
down_revision: Union[str, None] = '58e7e131ddb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'deleted_at')
    # ### end Alembic commands ###
