"""57_add_is_visible_column_in_provider_table

Revision ID: 2d3ebf21c1bf
Revises: edbfad4663bc
Create Date: 2025-03-31 17:52:29.200109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3ebf21c1bf'
down_revision: Union[str, None] = 'edbfad4663bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default=sa.text("true")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'is_visible')
    # ### end Alembic commands ###
