"""58_add_indexing

Revision ID: 2f161442f0c5
Revises: 2d3ebf21c1bf
Create Date: 2025-04-10 12:04:15.137864

"""
from alembic import op
from typing import Sequence, Union
# revision identifiers, used by Alembic.
revision: str = '2f161442f0c5'
down_revision: Union[str, None] = '2d3ebf21c1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")  # Ends the current transaction

    # op.execute("""
    #     CREATE INDEX CONCURRENTLY idx_sessions_parking_lot_id_start_time
    #     ON sessions(parking_lot_id, session_start_time)
    #     WHERE session_start_time >= NOW() - INTERVAL '31 days';
    # """)
    op.execute("""
        CREATE INDEX CONCURRENTLY idx_sessions_active_partial
        ON sessions(id)
        WHERE is_active = TRUE;
    """)
    op.execute("""
        CREATE INDEX CONCURRENTLY idx_sessions_payment_partial
        ON sessions(id) 
        WHERE is_waiting_for_payment = TRUE;
    """)

    #--------------Session log table--------
    op.execute("""
        CREATE INDEX CONCURRENTLY idx_session_log_fk_sessions 
        ON session_log(fk_sessions);
    """)
    #--------------violation table--------

    op.execute("""
        CREATE INDEX CONCURRENTLY idx_violation_session_id 
        ON violation(session_id);
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")  # Ends the current transaction

    # op.execute("""
    #     DROP INDEX CONCURRENTLY IF EXISTS idx_sessions_parking_lot_id_start_time
    # """)
    op.execute("""
        DROP INDEX CONCURRENTLY IF EXISTS idx_sessions_active_partial
    """)
    op.execute("""
        DROP INDEX CONCURRENTLY IF EXISTS idx_sessions_payment_partial
    """)
    # --------------Session log table--------
    op.execute("""
        DROP INDEX CONCURRENTLY IF EXISTS idx_session_log_fk_sessions
    """)
    # --------------violation table--------
    op.execute("""
        DROP INDEX CONCURRENTLY IF EXISTS idx_violation_session_id
    """)
    # ### end Alembic commands ###
