"""59_added_is_lpr_to_spot_in_sessions

Revision ID: 77469b5e0b7c
Revises: 2f161442f0c5
Create Date: 2025-04-21 16:48:43.340729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77469b5e0b7c'
down_revision: Union[str, None] = '2f161442f0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('is_lpr_to_spot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'is_lpr_to_spot')
    # ### end Alembic commands ###
