"""60_add_provider_api_request_type_and_api_request_endpoint_in_provider_table

Revision ID: 9f857e88004b
Revises: 77469b5e0b7c
Create Date: 2025-04-23 16:55:21.632268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f857e88004b'
down_revision: Union[str, None] = '77469b5e0b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('provider_api_request_type', sa.String(), server_default="sgconnect", nullable=False))
    op.add_column('provider', sa.Column('api_request_endpoint', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'api_request_endpoint')
    op.drop_column('provider', 'provider_api_request_type')
    # ### end Alembic commands ###
