"""61_set_grace_period_default_value_to_0

Revision ID: 289b3d966239
Revises: 9f857e88004b
Create Date: 2025-05-02 15:48:58.272107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '289b3d966239'
down_revision: Union[str, None] = '9f857e88004b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Fill existing NULLs with 0 first
    op.execute("UPDATE connect_parkinglot SET grace_period = 0 WHERE grace_period IS NULL")

    op.alter_column('connect_parkinglot', 'grace_period',
               existing_type=sa.INTEGER(),
               server_default='0',
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connect_parkinglot', 'grace_period',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
